# Generated by Django 3.2.3 on 2021-05-20 14:17

import apps.users.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.users.managers.CustomUserManager()),
            ],
        ),
    ]
