# Generated by Django 3.2.7 on 2021-09-08 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uuid',
            new_name='user_uuid',
        ),
    ]
