# Generated by Django 3.2.7 on 2021-09-08 18:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_uuid_user_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_uuid',
            field=models.UUIDField(db_column='uuid', db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
