# Generated by Django 3.2.3 on 2021-06-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('FORCE_CHANGE_PASSWORD', 'FORCE_CHANGE_PASSWORD'), ('ARCHIVED', 'ARCHIVED'), ('CONFIRMED', 'CONFIRMED'), ('UNCONFIRMED', 'UNCONFIRMED')], default='UNCONFIRMED', max_length=40, null=True),
        ),
    ]
